# API Redirect (if needed)
[[redirects]]
  from = "/api/*"
  to = "https://corsproxy.io/?http://deenfit-001-site1.qtempurl.com/api/:splat"
  status = 200
  force = true

# React SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
